version: "3.7"
services:
  web:
    image: deklanw/postmodernly:latest
    depends_on:
      - db
      - redis
    networks:
      - web
      - internal
    env_file: 
      - './docker-compose.env'
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:postmodernly-gql.deklan.dev"
      - "traefik.docker.network=web"
      - "traefik.port=4000"
  db:
    image: postgres:11.3
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: 
      - './docker-compose.env'
    networks:
      - internal
  redis:
    image: redis:5.0.5
    env_file: 
      - './docker-compose.env'
    networks:
      - internal
networks:
  web:
    external: true
  internal:
    external: false