version: "3.7"
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8082:80"
    depends_on:
      - web
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  web:
    image: postmodernly-backend
    depends_on:
      - db
      - redis
    networks:
      - webnet
    env_file: 
      - './docker-compose.env'
  db:
    image: postgres:11.3
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: 
      - './docker-compose.env'
    networks:
      - webnet
  redis:
    image: redis:5.0.5
    env_file: 
      - './docker-compose.env'
    networks:
      - webnet
networks:
  webnet: